#!/usr/bin/python3
# -*- coding: utf-8 -*-

try:
    from sys import argv, stdin
    
    if len(argv) == 1 or argv[1] == '-':
        arg = stdin.read()
        for arg in stdin.read():
            print(bin(int(arg))[2:])
    else:
        assert len(argv) == 2
        print(bin(int(argv[1]))[2:])
except:
    exit(1)
